### ISSUE TITLE
Please increment the version...

### ISSUE THREAD

**Issue by dhardtke** [Fuzzyma/svg.select.js#7]
Hey,

I think this is the fault for the issue I have right now:

	bower.cmd install svg.resize.js
	bower svg.resize.js#*       not-cached git://github.com/Fuzzyma/svg.resize.js.git#*
	bower svg.resize.js#*          resolve git://github.com/Fuzzyma/svg.resize.js.git#*
	bower svg.resize.js#*         download https://github.com/Fuzzyma/svg.resize.js/archive/1.1.0.tar.gz
	bower svg.resize.js#*          extract archive.tar.gz
	bower svg.resize.js#*         resolved git://github.com/Fuzzyma/svg.resize.js.git#1.1.0
	bower svg.select.js#^1.0.4  not-cached git://github.com/Fuzzyma/svg.select.js.git#^1.0.4
	bower svg.select.js#^1.0.4     resolve git://github.com/Fuzzyma/svg.select.js.git#^1.0.4
	bower svg.js#^2.0.2         not-cached git://github.com/wout/svg.js.git#^2.0.2
	bower svg.js#^2.0.2            resolve git://github.com/wout/svg.js.git#^2.0.2
	bower svg.select.js#^1.0.4    download https://github.com/Fuzzyma/svg.select.js/archive/1.0.4.tar.gz
	bower svg.js#^2.0.2           download https://github.com/wout/svg.js/archive/2.0.2.tar.gz
	bower svg.select.js#^1.0.4     extract archive.tar.gz
	bower svg.select.js#^1.0.4    resolved git://github.com/Fuzzyma/svg.select.js.git#1.0.4
	bower svg.js#1.1.x          not-cached git://github.com/wout/svg.js.git#1.1.x
	bower svg.js#1.1.x             resolve git://github.com/wout/svg.js.git#1.1.x
	bower svg.js#1.1.x            download https://github.com/wout/svg.js/archive/1.1.0.tar.gz
	bower svg.js#^2.0.2            extract archive.tar.gz
	bower svg.js#^2.0.2           resolved git://github.com/wout/svg.js.git#2.0.2
	bower svg.js#1.1.x             extract archive.tar.gz
	bower svg.js#1.1.x            resolved git://github.com/wout/svg.js.git#1.1.0
	bower                        ECONFLICT Unable to find suitable version for svg.js

I think this could be due to bower loading the "old" bower.json with "dependencies" set to SVG.js version 1.x... but I'm not 100% sure.

**Comment by Fuzzyma** [comment]
done. Hope it helps!

**Comment by dhardtke** [comment]
could you update the "dependencies" section in svg.resize.js' bower.json as well? it's still failing..
:+1:

**Comment by Fuzzyma** [comment]
The dependencies of svg.resize.js is correct. The caret makes sure that the most recent version of svg.select.js is used.

**Comment by dhardtke** [comment]
Okay - then I have no idea anymore why bower complains about not being able to find a proper SVG.js version fitting for svg.resize.js

**Comment by Fuzzyma** [comment]
Thats what I get:

```
bower svg.resize.js#*           cached git://github.com/Fuzzyma/svg.resize.js.git#1.0.0
bower svg.resize.js#*         validate 1.0.0 against git://github.com/Fuzzyma/svg.resize.js.git#*
bower svg.resize.js#*              new version for git://github.com/Fuzzyma/svg.resize.js.git#*
bower svg.resize.js#*          resolve git://github.com/Fuzzyma/svg.resize.js.git#*
bower svg.resize.js#*         download https://github.com/Fuzzyma/svg.resize.js/archive/1.1.0.tar.gz
bower svg.resize.js#*          extract archive.tar.gz
bower svg.resize.js#*         resolved git://github.com/Fuzzyma/svg.resize.js.git#1.1.0
bower svg.js#^2.0.2         not-cached git://github.com/wout/svg.js.git#^2.0.2
bower svg.js#^2.0.2            resolve git://github.com/wout/svg.js.git#^2.0.2
bower svg.js#^2.0.2           download https://github.com/wout/svg.js/archive/2.0.2.tar.gz
bower svg.select.js#^1.0.4  not-cached git://github.com/Fuzzyma/svg.select.js.git#^1.0.4
bower svg.select.js#^1.0.4     resolve git://github.com/Fuzzyma/svg.select.js.git#^1.0.4
bower svg.select.js#^1.0.4    download https://github.com/Fuzzyma/svg.select.js/archive/1.0.5.tar.gz
bower svg.select.js#^1.0.4     extract archive.tar.gz
bower svg.js#^2.0.2            extract archive.tar.gz
bower svg.select.js#^1.0.4    resolved git://github.com/Fuzzyma/svg.select.js.git#1.0.5
bower svg.js#^2.0.2           resolved git://github.com/wout/svg.js.git#2.0.2
bower svg.resize.js#~1.1.0     install svg.resize.js#1.1.0
bower svg.select.js#^1.0.4     install svg.select.js#1.0.5
bower svg.js#^2.0.2            install svg.js#2.0.2

svg.resize.js#1.1.0 bower_components\svg.resize.js
├── svg.js#2.0.2
└── svg.select.js#1.0.5

svg.select.js#1.0.5 bower_components\svg.select.js
└── svg.js#2.0.2

svg.js#2.0.2 bower_components\svg.js
```

So no problem at my side. You maybe should clean your bower cache?

**Comment by dhardtke** [comment]
You're right. After executing ```bower prune``` everything works perfectly.
